(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ca(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}
var l=ca(this),da="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function ea(a,b){if(b){var c=l;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&da(c,a,{configurable:!0,writable:!0,value:b})}}
ea("Promise",function(a){function b(h){this.b=0;this.g=void 0;this.a=[];var k=this.c();try{h(k.resolve,k.reject)}catch(m){k.reject(m)}}function c(){this.a=null}function d(h){return h instanceof b?h:new b(function(k){k(h)})}if(a)return a;c.prototype.b=function(h){if(null==this.a){this.a=[];var k=this;this.c(function(){k.g()})}this.a.push(h)};var e=l.setTimeout;c.prototype.c=function(h){e(h,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var h=this.a;this.a=[];for(var k=0;k<h.length;++k){var m=
h[k];h[k]=null;try{m()}catch(q){this.f(q)}}}this.a=null};c.prototype.f=function(h){this.c(function(){throw h;})};b.prototype.c=function(){function h(q){return function(B){m||(m=!0,q.call(k,B))}}var k=this,m=!1;return{resolve:h(this.F),reject:h(this.f)}};b.prototype.F=function(h){if(h===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(h instanceof b)this.G(h);else{a:switch(typeof h){case "object":var k=null!=h;break a;case "function":k=!0;break a;default:k=!1}k?this.o(h):this.h(h)}};
b.prototype.o=function(h){var k=void 0;try{k=h.then}catch(m){this.f(m);return}"function"==typeof k?this.I(k,h):this.h(h)};b.prototype.f=function(h){this.i(2,h)};b.prototype.h=function(h){this.i(1,h)};b.prototype.i=function(h,k){if(0!=this.b)throw Error("Cannot settle("+h+", "+k+"): Promise already settled in state"+this.b);this.b=h;this.g=k;this.j()};b.prototype.j=function(){if(null!=this.a){for(var h=0;h<this.a.length;++h)g.b(this.a[h]);this.a=null}};var g=new c;b.prototype.G=function(h){var k=this.c();
h.w(k.resolve,k.reject)};b.prototype.I=function(h,k){var m=this.c();try{h.call(k,m.resolve,m.reject)}catch(q){m.reject(q)}};b.prototype.then=function(h,k){function m(G,P){return"function"==typeof G?function(Ia){try{q(G(Ia))}catch(Ja){B(Ja)}}:P}var q,B,Ka=new b(function(G,P){q=G;B=P});this.w(m(h,q),m(k,B));return Ka};b.prototype.catch=function(h){return this.then(void 0,h)};b.prototype.w=function(h,k){function m(){switch(q.b){case 1:h(q.g);break;case 2:k(q.g);break;default:throw Error("Unexpected state: "+
q.b);}}var q=this;null==this.a?g.b(m):this.a.push(m)};b.resolve=d;b.reject=function(h){return new b(function(k,m){m(h)})};b.race=function(h){return new b(function(k,m){for(var q=ba(h),B=q.next();!B.done;B=q.next())d(B.value).w(k,m)})};b.all=function(h){var k=ba(h),m=k.next();return m.done?d([]):new b(function(q,B){function Ka(Ia){return function(Ja){G[Ia]=Ja;P--;0==P&&q(G)}}var G=[],P=0;do G.push(void 0),P++,d(m.value).w(Ka(G.length-1),B),m=k.next();while(!m.done)})};return b});
function fa(){fa=function(){};l.Symbol||(l.Symbol=ha)}function ia(a,b){this.a=a;da(this,"description",{configurable:!0,writable:!0,value:b})}ia.prototype.toString=function(){return this.a};var ha=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new ia("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function ja(){fa();var a=l.Symbol.iterator;a||(a=l.Symbol.iterator=l.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&da(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ka(aa(this))}});ja=function(){}}function ka(a){ja();a={next:a};a[l.Symbol.iterator]=function(){return this};return a}function la(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}
function ma(){this.h=!1;this.f=null;this.j=void 0;this.a=1;this.g=this.c=0;this.i=this.b=null}function na(a){if(a.h)throw new TypeError("Generator is already running");a.h=!0}f=ma.prototype;f.A=function(a){this.j=a};function oa(a,b){a.b={K:b,L:!0};a.a=a.c||a.g}f.return=function(a){this.b={return:a};this.a=this.g};f.Ma=function(a){this.b={u:a};this.a=this.g};function pa(a,b,c){a.a=c;return{value:b}}
f.zc=function(a,b){a=ba(a);var c=a.next();la(c);if(c.done)this.j=c.value,this.a=b;else return this.f=a,pa(this,c.value,b)};f.u=function(a){this.a=a};f.Na=function(){this.a=0};f.ab=function(a){this.c=0;this.g=a||0};function qa(a,b){a.a=b;a.c=0}function ra(a){a.c=0;var b=a.b.K;a.b=null;return b}f.Y=function(a,b,c){c?this.i[c]=this.b:this.i=[this.b];this.c=a||0;this.g=b||0};
f.Oa=function(a,b){b=this.i.splice(b||0)[0];(b=this.b=this.b||b)?b.L?this.a=this.c||this.g:void 0!=b.u&&this.g<b.u?(this.a=b.u,this.b=null):this.a=this.g:this.a=a};f.aa=function(a){return new sa(a)};function sa(a){this.b=a;this.a=[];for(var b in a)this.a.push(b);this.a.reverse()}sa.prototype.c=function(){for(;0<this.a.length;){var a=this.a.pop();if(a in this.b)return a}return null};function ta(a){this.a=new ma;this.b=a}
function ua(a,b){na(a.a);var c=a.a.f;if(c)return va(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.a.return);a.a.return(b);return wa(a)}function va(a,b,c,d){try{var e=b.call(a.a.f,c);la(e);if(!e.done)return a.a.h=!1,e;var g=e.value}catch(h){return a.a.f=null,oa(a.a,h),wa(a)}a.a.f=null;d.call(a.a,g);return wa(a)}
function wa(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.h=!1,{value:b.value,done:!1}}catch(c){a.a.j=void 0,oa(a.a,c)}a.a.h=!1;if(a.a.b){b=a.a.b;a.a.b=null;if(b.L)throw b.K;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function xa(a){this.next=function(b){na(a.a);a.a.f?b=va(a,a.a.f.next,b,a.a.A):(a.a.A(b),b=wa(a));return b};this.throw=function(b){na(a.a);a.a.f?b=va(a,a.a.f["throw"],b,a.a.A):(oa(a.a,b),b=wa(a));return b};this.return=function(b){return ua(a,b)};ja();this[Symbol.iterator]=function(){return this}}function ya(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function g(h){h.done?d(h.value):Promise.resolve(h.value).then(b,c).then(g,e)}g(a.next())})}
var n=this||self;function za(a){a=a.split(".");for(var b=n,c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b}function Aa(){}
function Ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function Ca(a){var b=Ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function Da(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function Ea(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var Fa=Date.now||function(){return+new Date};
function Ga(a,b){a=a.split(".");var c=n;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function Ha(a,b){function c(){}c.prototype=b.prototype;a.J=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.S=function(d,e,g){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var La=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ma=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)},Na=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,g=0;g<c;g++)g in e&&(d[g]=b.call(void 0,e[g],g,a));return d};function Oa(a){return Array.prototype.concat.apply([],arguments)}function Pa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Qa(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};function Ra(a){if(8192>=a.length)return String.fromCharCode.apply(null,a);for(var b="",c=0;c<a.length;c+=8192)b+=String.fromCharCode.apply(null,Qa(a,c,c+8192));return b};function Sa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ta(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};var Ua=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function p(a,b){return-1!=a.indexOf(b)}function Va(a,b){return a<b?-1:a>b?1:0};var r;a:{var Wa=n.navigator;if(Wa){var Xa=Wa.userAgent;if(Xa){r=Xa;break a}}r=""};function Ya(a){Ya[" "](a);return a}Ya[" "]=Aa;var Za=p(r,"Opera"),t=p(r,"Trident")||p(r,"MSIE"),$a=p(r,"Edge"),ab=p(r,"Gecko")&&!(p(r.toLowerCase(),"webkit")&&!p(r,"Edge"))&&!(p(r,"Trident")||p(r,"MSIE"))&&!p(r,"Edge"),bb=p(r.toLowerCase(),"webkit")&&!p(r,"Edge"),cb=p(r,"Macintosh");function db(){var a=n.document;return a?a.documentMode:void 0}var eb;
a:{var fb="",gb=function(){var a=r;if(ab)return/rv:([^\);]+)(\)|;)/.exec(a);if($a)return/Edge\/([\d\.]+)/.exec(a);if(t)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(bb)return/WebKit\/(\S+)/.exec(a);if(Za)return/(?:Version)[ \/]?(\S+)/.exec(a)}();gb&&(fb=gb?gb[1]:"");if(t){var hb=db();if(null!=hb&&hb>parseFloat(fb)){eb=String(hb);break a}}eb=fb}var ib=eb,jb={},kb;if(n.document&&t){var lb=db();kb=lb?lb:parseInt(ib,10)||void 0}else kb=void 0;var mb=kb;var nb={},ob=null;function pb(a,b){void 0===b&&(b=0);qb();b=nb[b];for(var c=[],d=0;d<a.length;d+=3){var e=a[d],g=d+1<a.length,h=g?a[d+1]:0,k=d+2<a.length,m=k?a[d+2]:0,q=e>>2;e=(e&3)<<4|h>>4;h=(h&15)<<2|m>>6;m&=63;k||(m=64,g||(h=64));c.push(b[q],b[e],b[h]||"",b[m]||"")}return c.join("")}function rb(a){var b=a.length,c=3*b/4;c%3?c=Math.floor(c):p("=.",a[b-1])&&(c=p("=.",a[b-2])?c-2:c-1);var d=new Uint8Array(c),e=0;sb(a,function(g){d[e++]=g});return d.subarray(0,e)}
function sb(a,b){function c(m){for(;d<a.length;){var q=a.charAt(d++),B=ob[q];if(null!=B)return B;if(!/^[\s\xa0]*$/.test(q))throw Error("Unknown base64 encoding at char: "+q);}return m}qb();for(var d=0;;){var e=c(-1),g=c(0),h=c(64),k=c(64);if(64===k&&-1===e)break;b(e<<2|g>>4);64!=h&&(b(g<<4&240|h>>2),64!=k&&b(h<<6&192|k))}}
function qb(){if(!ob){ob={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));nb[c]=d;for(var e=0;e<d.length;e++){var g=d[e];void 0===ob[g]&&(ob[g]=e)}}}};var u=0,v=0;function tb(a){var b=a>>>0;a=Math.floor((a-b)/4294967296)>>>0;u=b;v=a}function w(a){var b=0>a;a=Math.abs(a);var c=a>>>0;a=Math.floor((a-c)/4294967296);a>>>=0;b&&(a=~a>>>0,c=(~c>>>0)+1,4294967295<c&&(c=0,a++,4294967295<a&&(a=0)));u=c;v=a}function ub(a){var b=0>a;a=2*Math.abs(a);tb(a);a=u;var c=v;b&&(0==a?0==c?c=a=4294967295:(c--,a=4294967295):a--);u=a;v=c}
function vb(a){var b=0>a?1:0;a=b?-a:a;if(0===a)0<1/a?u=v=0:(v=0,u=2147483648);else if(isNaN(a))v=0,u=2147483647;else if(3.4028234663852886E38<a)v=0,u=(b<<31|2139095040)>>>0;else if(1.1754943508222875E-38>a)a=Math.round(a/Math.pow(2,-149)),v=0,u=(b<<31|a)>>>0;else{var c=Math.floor(Math.log(a)/Math.LN2);a*=Math.pow(2,-c);a=Math.round(8388608*a)&8388607;v=0;u=(b<<31|c+127<<23|a)>>>0}}
function wb(a){var b=a.charCodeAt(4),c=a.charCodeAt(5),d=a.charCodeAt(6),e=a.charCodeAt(7);u=a.charCodeAt(0)+(a.charCodeAt(1)<<8)+(a.charCodeAt(2)<<16)+(a.charCodeAt(3)<<24)>>>0;v=b+(c<<8)+(d<<16)+(e<<24)>>>0}function xb(a,b,c){var d=b>>31;c(a<<1^d,(b<<1|a>>>31)^d)}
function yb(a){function b(h,k){for(var m=0;8>m&&(1!==h||0<k);m++)k=h*e[m]+k,e[m]=k&255,k>>>=8}function c(){for(var h=0;8>h;h++)e[h]=~e[h]&255}var d=!1;"-"===a[0]&&(d=!0,a=a.slice(1));for(var e=[0,0,0,0,0,0,0,0],g=0;g<a.length;g++)b(10,a.charCodeAt(g)-48);d&&(c(),b(1,1));return Ra(e)};function x(a,b){this.a=a;this.b=b}function zb(a){return new x((a.a>>>1|(a.b&1)<<31)>>>0,a.b>>>1>>>0)}function Ab(a){return new x(a.a<<1>>>0,(a.b<<1|a.a>>>31)>>>0)}f=x.prototype;f.Ta=function(){return!!(this.a&1)};f.add=function(a){return new x((this.a+a.a&4294967295)>>>0>>>0,((this.b+a.b&4294967295)>>>0)+(4294967296<=this.a+a.a?1:0)>>>0)};f.sub=function(a){return new x((this.a-a.a&4294967295)>>>0>>>0,((this.b-a.b&4294967295)>>>0)-(0>this.a-a.a?1:0)>>>0)};
function Bb(a){var b=a&65535,c=a>>>16;a=10*b+65536*(0*b&65535)+65536*(10*c&65535);for(b=0*c+(0*b>>>16)+(10*c>>>16);4294967296<=a;)a-=4294967296,b+=1;return new x(a>>>0,b>>>0)}f.toString=function(){for(var a="",b=this;0!=b.a||0!=b.b;){var c=new x(0,0);b=new x(b.a,b.b);for(var d=new x(10,0),e=new x(1,0);!(d.b&2147483648);)d=Ab(d),e=Ab(e);for(;0!=e.a||0!=e.b;)0>=(d.b<b.b||d.b==b.b&&d.a<b.a?-1:d.b==b.b&&d.a==b.a?0:1)&&(c=c.add(e),b=b.sub(d)),d=zb(d),e=zb(e);c=[c,b];b=c[0];a=c[1].a+a}""==a&&(a="0");return a};
function Cb(a){for(var b=new x(0,0),c=new x(0,0),d=0;d<a.length;d++){if("0">a[d]||"9"<a[d])return null;c.a=parseInt(a[d],10);var e=Bb(b.a);b=Bb(b.b);b.b=b.a;b.a=0;b=e.add(b).add(c)}return b}f.La=function(){return new x(this.a,this.b)};function y(a,b){this.a=a;this.b=b}y.prototype.add=function(a){return new y((this.a+a.a&4294967295)>>>0>>>0,((this.b+a.b&4294967295)>>>0)+(4294967296<=this.a+a.a?1:0)>>>0)};
y.prototype.sub=function(a){return new y((this.a-a.a&4294967295)>>>0>>>0,((this.b-a.b&4294967295)>>>0)-(0>this.a-a.a?1:0)>>>0)};y.prototype.c=function(){return new y(this.a,this.b)};y.prototype.toString=function(){var a=0!=(this.b&2147483648),b=new x(this.a,this.b);a&&(b=(new x(0,0)).sub(b));return(a?"-":"")+b.toString()};function Db(a){var b=0<a.length&&"-"==a[0];b&&(a=a.substring(1));a=Cb(a);if(null===a)return null;b&&(a=(new x(0,0)).sub(a));return new y(a.a,a.b)};function Eb(){this.a=[]}f=Eb.prototype;f.length=function(){return this.a.length};function Fb(a){var b=a.a;a.a=[];return b}function z(a,b,c){for(;0<c||127<b;)a.a.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.a.push(b)}function A(a,b,c){C(a,b);C(a,c)}function Gb(a,b,c){xb(b,c,function(d,e){z(a,d>>>0,e>>>0)})}function D(a,b){for(;127<b;)a.a.push(b&127|128),b>>>=7;a.a.push(b)}function E(a,b){if(0<=b)D(a,b);else{for(var c=0;9>c;c++)a.a.push(b&127|128),b>>=7;a.a.push(1)}}
function Hb(a,b){D(a,(b<<1^b>>31)>>>0)}function Ib(a,b){wb(yb(b));xb(u,v,function(c,d){z(a,c>>>0,d>>>0)})}f.yc=function(a){this.a.push(a>>>0&255)};f.xc=function(a){this.a.push(a>>>0&255);this.a.push(a>>>8&255)};function C(a,b){a.a.push(b>>>0&255);a.a.push(b>>>8&255);a.a.push(b>>>16&255);a.a.push(b>>>24&255)}function Jb(a,b){tb(b);C(a,u);C(a,v)}f.ub=function(a){this.a.push(a>>>0&255)};f.tb=function(a){this.a.push(a>>>0&255);this.a.push(a>>>8&255)};
function Kb(a,b){a.a.push(b>>>0&255);a.a.push(b>>>8&255);a.a.push(b>>>16&255);a.a.push(b>>>24&255)}
function Lb(a,b){var c=b;c=(b=0>c?1:0)?-c:c;if(0===c)v=0<1/c?0:2147483648,u=0;else if(isNaN(c))v=2147483647,u=4294967295;else if(1.7976931348623157E308<c)v=(b<<31|2146435072)>>>0,u=0;else if(2.2250738585072014E-308>c)c/=Math.pow(2,-1074),v=(b<<31|c/4294967296)>>>0,u=c>>>0;else{var d=c,e=0;if(2<=d)for(;2<=d&&1023>e;)e++,d/=2;else for(;1>d&&-1022<e;)d*=2,e--;c*=Math.pow(2,-e);v=(b<<31|e+1023<<20|1048576*c&1048575)>>>0;u=4503599627370496*c>>>0}C(a,u);C(a,v)}
f.Ha=function(a){this.a.push.apply(this.a,a)};function Mb(){this.c=[];this.b=0;this.a=new Eb;this.f=[]}function Nb(a,b){var c=Fb(a.a);a.c.push(c);a.c.push(b);a.b+=c.length+b.length}function F(a,b){H(a,b,2);b=Fb(a.a);a.c.push(b);a.b+=b.length;b.push(a.b);return b}function I(a,b){var c=b.pop();for(c=a.b+a.a.length()-c;127<c;)b.push(c&127|128),c>>>=7,a.b++;b.push(c);a.b++}f=Mb.prototype;f.Va=function(a,b,c){null!=a&&null!=b&&null!=c&&Nb(this,a.subarray(b,c))};f.Ia=function(){this.c=[];Fb(this.a);this.b=0;this.f=[]};
function Ob(a){for(var b=new Uint8Array(a.b+a.a.length()),c=a.c,d=c.length,e=0,g=0;g<d;g++){var h=c[g];b.set(h,e);e+=h.length}c=Fb(a.a);b.set(c,e);a.c=[b];return b}f.ha=function(a){return pb(Ob(this),a)};f.T=function(a){this.f.push(F(this,a))};f.X=function(){I(this,this.f.pop())};function H(a,b,c){D(a.a,8*b+c)}
f.rb=function(a,b,c){switch(a){case 1:null!=c&&(H(this,b,1),Lb(this.a,c));break;case 2:null!=c&&(H(this,b,5),a=this.a,vb(c),C(a,u));break;case 3:null!=c&&null!=c&&(H(this,b,0),a=this.a,w(c),z(a,u,v));break;case 4:null!=c&&null!=c&&(H(this,b,0),a=this.a,w(c),z(a,u,v));break;case 5:null!=c&&Pb(this,b,c);break;case 6:null!=c&&(H(this,b,1),Jb(this.a,c));break;case 7:null!=c&&(H(this,b,5),C(this.a,c));break;case 8:Qb(this,b,c);break;case 9:J(this,b,c);break;case 12:Rb(this,b,c);break;case 13:null!=c&&
Sb(this,b,c);break;case 14:Tb(this,b,c);break;case 15:null!=c&&(H(this,b,5),Kb(this.a,c));break;case 16:null!=c&&(H(this,b,1),a=this.a,w(c),A(a,u,v));break;case 17:null!=c&&null!=c&&(H(this,b,0),Hb(this.a,c));break;case 18:null!=c&&null!=c&&(H(this,b,0),a=this.a,ub(c),z(a,u,v))}};function Sb(a,b,c){null!=c&&(H(a,b,0),D(a.a,c))}function Pb(a,b,c){null!=c&&(H(a,b,0),E(a.a,c))}f.wc=function(a,b){null!=b&&null!=b&&(H(this,a,0),Ib(this.a,b))};function Qb(a,b,c){null!=c&&(H(a,b,0),a.a.a.push(c?1:0))}
function Tb(a,b,c){null!=c&&(H(a,b,0),E(a.a,c))}
function J(a,b,c){if(null!=c){b=F(a,b);for(var d=a.a,e=0;e<c.length;e++){var g=c.charCodeAt(e);if(128>g)d.a.push(g);else if(2048>g)d.a.push(g>>6|192),d.a.push(g&63|128);else if(65536>g)if(55296<=g&&56319>=g&&e+1<c.length){var h=c.charCodeAt(e+1);56320<=h&&57343>=h&&(g=1024*(g-55296)+h-56320+65536,d.a.push(g>>18|240),d.a.push(g>>12&63|128),d.a.push(g>>6&63|128),d.a.push(g&63|128),e++)}else d.a.push(g>>12|224),d.a.push(g>>6&63|128),d.a.push(g&63|128)}I(a,b)}}
function Rb(a,b,c){null!=c&&(c=c.constructor===Uint8Array?c:c.constructor===ArrayBuffer?new Uint8Array(c):c.constructor===Array?new Uint8Array(c):c.constructor===String?rb(c):new Uint8Array(0),H(a,b,2),D(a.a,c.length),Nb(a,c))}f.vb=function(a,b,c){null!=b&&(a=F(this,a),c(b,this),I(this,a))};f.wb=function(a,b,c){null!=b&&(H(this,1,3),H(this,2,0),E(this.a,a),a=F(this,3),c(b,this),I(this,a),H(this,1,4))};f.sb=function(a,b,c){null!=b&&(H(this,a,3),c(b,this),H(this,a,4))};
f.dc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Pb(this,a,b[c])};f.ec=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Pb(this,a,parseInt(d,10))}};f.fc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){H(this,a,0);var e=this.a;w(d);z(e,u,v)}}};f.pc=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var g=c(b[e]),h=d(b[e]);H(this,a,1);A(this.a,g,h)}};
f.qc=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var g=c(b[e]),h=d(b[e]);H(this,a,0);z(this.a,g,h)}};f.rc=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var g=c(b[e]),h=d(b[e]);H(this,a,0);Gb(this.a,g>>>0,h>>>0)}};f.hc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=Db(e),H(this,d,0),z(this.a,e.a,e.b))}};f.sc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Sb(this,a,b[c])};
f.tc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Sb(this,a,parseInt(d,10))}};f.uc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){H(this,a,0);var e=this.a;w(d);z(e,u,v)}}};f.vc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=Cb(e),H(this,d,0),z(this.a,e.a,e.b))}};f.mc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(H(this,a,0),Hb(this.a,d))}};
f.nc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){H(this,a,0);var e=this.a;ub(d);z(e,u,v)}}};f.oc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(H(this,a,0),Ib(this.a,d))}};f.Zb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(H(this,a,5),C(this.a,d))}};f.$b=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(H(this,a,1),Jb(this.a,d))}};
f.ac=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=Cb(e),H(this,d,1),A(this.a,e.a,e.b))}};f.jc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(H(this,a,5),Kb(this.a,d))}};f.kc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){H(this,a,1);var e=this.a;w(d);A(e,u,v)}}};f.lc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=Db(e),H(this,d,1),A(this.a,e.a,e.b))}};
f.bc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){H(this,a,5);var e=this.a;vb(d);C(e,u)}}};f.Xb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(H(this,a,1),Lb(this.a,d))}};f.Vb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Qb(this,a,b[c])};f.Yb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Tb(this,a,b[c])};f.Wb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Rb(this,a,b[c])};
f.ic=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++){var e=F(this,a);c(b[d],this);I(this,e)}};f.cc=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++)H(this,a,3),c(b[d],this),H(this,a,4)};f.Eb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++)E(this.a,b[c]);I(this,a)}};f.Fb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++)E(this.a,parseInt(b[c],10));I(this,a)}};
f.Gb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++){var d=this.a;w(b[c]);z(d,u,v)}I(this,a)}};f.Ob=function(a,b,c,d){if(null!=b){a=F(this,a);for(var e=0;e<b.length;e++)A(this.a,c(b[e]),d(b[e]));I(this,a)}};f.Pb=function(a,b,c,d){if(null!=b){a=F(this,a);for(var e=0;e<b.length;e++)z(this.a,c(b[e]),d(b[e]));I(this,a)}};f.Qb=function(a,b,c,d){if(null!=b){a=F(this,a);for(var e=this.a,g=0;g<b.length;g++)Gb(e,c(b[g]),d(b[g]));I(this,a)}};
f.Hb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++){var d=Db(b[c]);z(this.a,d.a,d.b)}I(this,a)}};f.Rb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++)D(this.a,b[c]);I(this,a)}};f.Sb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++)D(this.a,parseInt(b[c],10));I(this,a)}};f.Tb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++){var d=this.a;w(b[c]);z(d,u,v)}I(this,a)}};
f.Ub=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++){var d=Cb(b[c]);z(this.a,d.a,d.b)}I(this,a)}};f.Lb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++)Hb(this.a,b[c]);I(this,a)}};f.Mb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++){var d=this.a;ub(b[c]);z(d,u,v)}I(this,a)}};f.Nb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++)Ib(this.a,b[c]);I(this,a)}};
f.Ab=function(a,b){if(null!=b&&b.length)for(H(this,a,2),D(this.a,4*b.length),a=0;a<b.length;a++)C(this.a,b[a])};f.Bb=function(a,b){if(null!=b&&b.length)for(H(this,a,2),D(this.a,8*b.length),a=0;a<b.length;a++)Jb(this.a,b[a])};f.Cb=function(a,b){if(null!=b&&b.length)for(H(this,a,2),D(this.a,8*b.length),a=0;a<b.length;a++){var c=Cb(b[a]);A(this.a,c.a,c.b)}};f.Ib=function(a,b){if(null!=b&&b.length)for(H(this,a,2),D(this.a,4*b.length),a=0;a<b.length;a++)Kb(this.a,b[a])};
f.Jb=function(a,b){if(null!=b&&b.length)for(H(this,a,2),D(this.a,8*b.length),a=0;a<b.length;a++){var c=this.a;w(b[a]);A(c,u,v)}};f.Kb=function(a,b){if(null!=b&&b.length)for(H(this,a,2),D(this.a,8*b.length),a=0;a<b.length;a++){var c=this.a;wb(yb(b[a]));A(c,u,v)}};f.Db=function(a,b){if(null!=b&&b.length)for(H(this,a,2),D(this.a,4*b.length),a=0;a<b.length;a++){var c=this.a;vb(b[a]);C(c,u)}};f.yb=function(a,b){if(null!=b&&b.length)for(H(this,a,2),D(this.a,8*b.length),a=0;a<b.length;a++)Lb(this.a,b[a])};
f.xb=function(a,b){if(null!=b&&b.length)for(H(this,a,2),D(this.a,b.length),a=0;a<b.length;a++)this.a.a.push(b[a]?1:0)};f.zb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++)E(this.a,b[c]);I(this,a)}};function Ub(){}var Vb="function"==typeof Uint8Array;Ub.prototype.j=function(){return this.h};var Wb=[];function Xb(a){var b=a.f+a.g;a.c[b]||(a.a=a.c[b]={})}function Yb(a,b){if(b<a.f){b+=a.g;var c=a.c[b];return c===Wb?a.c[b]=[]:c}if(a.a)return c=a.a[b],c===Wb?a.a[b]=[]:c}function K(a,b,c){a=Yb(a,b);return null==a?c:a}function L(a,b){a=Yb(a,b);a=null==a?a:!!a;return null==a?!1:a}function Zb(a,b,c){b<a.f?a.c[b+a.g]=c:(Xb(a),a.a[b]=c);return a}
function M(a,b,c,d){c!==d?Zb(a,b,c):b<a.f?a.c[b+a.g]=null:(Xb(a),delete a.a[b]);return a}function $b(a){if(a.b)for(var b in a.b){var c=a.b[b];if("array"==Ba(c))for(var d=0;d<c.length;d++)c[d]&&N(c[d]);else c&&N(c)}}function N(a){$b(a);return a.c}f=Ub.prototype;
f.M=Vb?function(){var a=Uint8Array.prototype.toJSON;Uint8Array.prototype.toJSON=function(){return pb(this)};try{return JSON.stringify(this.c&&N(this),ac)}finally{Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.c&&N(this),ac)};function ac(a,b){return"number"!==typeof b||!isNaN(b)&&Infinity!==b&&-Infinity!==b?b:String(b)}f.toString=function(){$b(this);return this.c.toString()};
f.Ka=function(a){if(this.a){this.b||(this.b={});var b=a.c;if(a.f){if(a.a())return this.b[b]||(this.b[b]=Na(this.a[b]||[],function(c){return new a.b(c)})),this.b[b]}else if(a.a())return!this.b[b]&&this.a[b]&&(this.b[b]=new a.b(this.a[b])),this.b[b];return this.a[b]}};f.$a=function(a,b){this.b||(this.b={});Xb(this);var c=a.c;a.f?(b=b||[],a.a()?(this.b[c]=b,this.a[c]=Na(b,function(d){return N(d)})):this.a[c]=b):a.a()?(this.b[c]=b,this.a[c]=b?N(b):b):this.a[c]=b;return this};f.W=function(){return new this.constructor(bc(N(this)))};
f.Ja=function(){return new this.constructor(bc(N(this)))};function bc(a){if(Array.isArray(a)){for(var b=Array(a.length),c=0;c<a.length;c++){var d=a[c];null!=d&&(b[c]="object"==typeof d?bc(d):d)}return b}if(Vb&&a instanceof Uint8Array)return new Uint8Array(a);b={};for(c in a)d=a[c],null!=d&&(b[c]="object"==typeof d?bc(d):d);return b};function cc(a){var b=a;a=dc;this.b=null;b||(b=[]);this.h=void 0;this.g=-1;this.c=b;a:{if(b=this.c.length){--b;var c=this.c[b];if(!(null===c||"object"!=typeof c||Array.isArray(c)||Vb&&c instanceof Uint8Array)){this.f=b- -1;this.a=c;break a}}this.f=Number.MAX_VALUE}this.i={};if(a)for(b=0;b<a.length;b++)c=a[b],c<this.f?(c+=-1,this.c[c]=this.c[c]||Wb):(Xb(this),this.a[c]=this.a[c]||Wb)}Ha(cc,Ub);var dc=[10];f=cc.prototype;
f.Wa=function(a){var b,c={mb:K(this,1,0),locale:K(this,2,""),R:K(this,4,""),ja:K(this,5,""),nb:K(this,6,""),Ca:K(this,7,""),Ea:L(this,8),Da:L(this,9),U:null==(b=Yb(this,10))?void 0:b,Fa:L(this,11)};a&&(c.O=this);return c};
f.Ya=function(){var a=new Mb;var b=this.getTenantId();0!==b&&Tb(a,1,b);b=this.getLocale();0<b.length&&J(a,2,b);b=K(this,4,"");0<b.length&&J(a,4,b);b=K(this,5,"");0<b.length&&J(a,5,b);b=K(this,6,"");0<b.length&&J(a,6,b);b=this.getInsecureHost();0<b.length&&J(a,7,b);(b=L(this,8))&&Qb(a,8,b);(b=L(this,9))&&Qb(a,9,b);b=Yb(this,10);if(0<b.length&&null!=b)for(var c=0;c<b.length;c++)J(a,10,b[c]);(b=L(this,11))&&Qb(a,11,b);return Ob(a)};f.getTenantId=function(){return K(this,1,0)};
f.kb=function(a){return M(this,1,a,0)};f.getLocale=function(){return K(this,2,"")};f.Za=function(a){return M(this,4,a,"")};f.bb=function(a){return M(this,5,a,"")};f.lb=function(a){return M(this,6,a,"")};f.getInsecureHost=function(){return K(this,7,"")};f.cb=function(a){return M(this,7,a,"")};f.fb=function(a){return M(this,8,a,!1)};f.eb=function(a){return M(this,9,a,!1)};f.P=function(a,b){var c=Yb(this,10);void 0!=b?c.splice(b,0,a):c.push(a);return this};f.V=function(){return Zb(this,10,[])};
f.gb=function(a){return M(this,11,a,!1)};function ec(){var a=GoogleDevelopersObject;return new cc(a?JSON.parse(a):null)};var fc="StopIteration"in n?n.StopIteration:{message:"StopIteration",stack:""};function gc(){}gc.prototype.next=function(){throw fc;};gc.prototype.a=function(){return this};function hc(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof hc)for(c=a.m(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}f=hc.prototype;f.l=function(){O(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};f.m=function(){O(this);return this.a.concat()};
f.ya=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(Q(this.b,c)&&this.b[c]==a)return!0}return!1};f.Z=function(a,b){if(this===a)return!0;if(this.c!=a.c)return!1;b=b||ic;O(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function ic(a,b){return a===b}f.za=function(){return 0==this.c};f.xa=function(){this.b={};this.f=this.c=this.a.length=0};
function O(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Q(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],Q(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}f.get=function(a,b){return Q(this.b,a)?this.b[a]:b};f.set=function(a,b){Q(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};f.forEach=function(a,b){for(var c=this.m(),d=0;d<c.length;d++){var e=c[d],g=this.get(e);a.call(b,g,e,this)}};
f.ob=function(){for(var a=new hc,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};f.Aa=function(){O(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};f.da=function(){return jc(this,!0)};f.ia=function(){return jc(this,!1)};function jc(a,b){O(a);var c=0,d=a.f,e=new gc;e.next=function(){if(d!=a.f)throw Error("The map has changed since the iterator was created");if(c>=a.a.length)throw fc;var g=a.a[c++];return b?g:a.b[g]};return e}
function Q(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function kc(a){if(a.l&&"function"==typeof a.l)return a.l();if("string"===typeof a)return a.split("");if(Ca(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function lc(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(Ca(a)||"string"===typeof a)Ma(a,b,c);else{if(a.m&&"function"==typeof a.m)var d=a.m();else if(a.l&&"function"==typeof a.l)d=void 0;else if(Ca(a)||"string"===typeof a){d=[];for(var e=a.length,g=0;g<e;g++)d.push(g)}else for(g in d=[],e=0,a)d[e++]=g;e=kc(a);g=e.length;for(var h=0;h<g;h++)b.call(c,e[h],d&&d[h],a)}};var mc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function nc(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var g=a[c].substring(0,d);e=a[c].substring(d+1)}else g=a[c];b(g,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function R(a,b){this.b=this.j=this.h="";this.f=null;this.i=this.c="";this.g=this.o=!1;if(a instanceof R){this.g=void 0!==b?b:a.g;oc(this,a.h);var c=a.j;S(this);this.j=c;c=a.b;S(this);this.b=c;pc(this,a.f);c=a.c;S(this);this.c=c;qc(this,rc(a.a));a=a.i;S(this);this.i=a}else a&&(c=String(a).match(mc))?(this.g=!!b,oc(this,c[1]||"",!0),a=c[2]||"",S(this),this.j=T(a),a=c[3]||"",S(this),this.b=T(a,!0),pc(this,c[4]),a=c[5]||"",S(this),this.c=T(a,!0),qc(this,c[6]||"",!0),a=c[7]||"",S(this),this.i=T(a)):(this.g=
!!b,this.a=new sc(null,this.g))}f=R.prototype;f.toString=function(){var a=[],b=this.h;b&&a.push(tc(b,uc,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(tc(b,uc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.f,null!=c&&a.push(":",String(c));if(c=this.c)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(tc(c,"/"==c.charAt(0)?vc:wc,!0));(c=this.a.toString())&&a.push("?",c);(c=this.i)&&a.push("#",tc(c,xc));return a.join("")};
f.resolve=function(a){var b=new R(this),c=!!a.h;c?oc(b,a.h):c=!!a.j;if(c){var d=a.j;S(b);b.j=d}else c=!!a.b;c?(d=a.b,S(b),b.b=d):c=null!=a.f;d=a.c;if(c)pc(b,a.f);else if(c=!!a.c){if("/"!=d.charAt(0))if(this.b&&!this.c)d="/"+d;else{var e=b.c.lastIndexOf("/");-1!=e&&(d=b.c.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(p(e,"./")||p(e,"/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var g=[],h=0;h<e.length;){var k=e[h++];"."==k?d&&h==e.length&&g.push(""):".."==k?((1<g.length||1==g.length&&""!=
g[0])&&g.pop(),d&&h==e.length&&g.push("")):(g.push(k),d=!0)}d=g.join("/")}else d=e}c?(S(b),b.c=d):c=""!==a.a.toString();c?qc(b,rc(a.a)):c=!!a.i;c&&(a=a.i,S(b),b.i=a);return b};function oc(a,b,c){S(a);a.h=c?T(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))}function pc(a,b){S(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.f=b}else a.f=null}function qc(a,b,c){S(a);b instanceof sc?(a.a=b,yc(a.a,a.g)):(c||(b=tc(b,zc)),a.a=new sc(b,a.g));return a}f.ib=function(a,b){return qc(this,a,b)};
f.ba=function(){return T(this.a.toString())};f.pa=function(){return this.a.toString()};f.hb=function(a,b){S(this);Array.isArray(b)||(b=[String(b)]);Ac(this.a,a,b);return this};f.ga=function(a){return this.a.l(a)};f.fa=function(a){return this.a.get(a)};f.Ba=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.f&&null==a.f||this.f==a.f)};
f.Ua=function(){S(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Fa()).toString(36);S(this);this.a.set("zx",a);return this};f.qa=function(a){S(this);Bc(this.a,a);return this};f.jb=function(a){this.o=a;return this};f.Ga=function(){return this.o};function S(a){if(a.o)throw Error("Tried to modify a read-only Uri");}f.ra=function(a){this.g=a;this.a&&yc(this.a,a);return this};
function T(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function tc(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Cc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function Cc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var uc=/[#\/\?@]/g,wc=/[#\?:]/g,vc=/[#\?]/g,zc=/[#\?@]/g,xc=/#/g;function sc(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b}
function U(a){a.a||(a.a=new hc,a.b=0,a.c&&nc(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}f=sc.prototype;f.na=function(){U(this);return this.b};f.add=function(a,b){U(this);this.c=null;a=V(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};function Bc(a,b){U(a);b=V(a,b);Q(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,Q(a.b,b)&&(delete a.b[b],a.c--,a.f++,a.a.length>2*a.c&&O(a)))}f.ka=function(){this.a=this.c=null;this.b=0};
f.oa=function(){U(this);return 0==this.b};function Dc(a,b){U(a);b=V(a,b);return Q(a.a.b,b)}f.la=function(a){var b=this.l();return 0<=La(b,a)};f.forEach=function(a,b){U(this);this.a.forEach(function(c,d){Ma(c,function(e){a.call(b,e,d,this)},this)},this)};f.m=function(){U(this);for(var a=this.a.l(),b=this.a.m(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};
f.l=function(a){U(this);var b=[];if("string"===typeof a)Dc(this,a)&&(b=Oa(b,this.a.get(V(this,a))));else{a=this.a.l();for(var c=0;c<a.length;c++)b=Oa(b,a[c])}return b};f.set=function(a,b){U(this);this.c=null;a=V(this,a);Dc(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};f.get=function(a,b){if(!a)return b;a=this.l(a);return 0<a.length?String(a[0]):b};function Ac(a,b,c){Bc(a,b);0<c.length&&(a.c=null,a.a.set(V(a,b),Pa(c)),a.b+=c.length)}
f.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.m(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.l(d);for(var g=0;g<d.length;g++){var h=e;""!==d[g]&&(h+="="+encodeURIComponent(String(d[g])));a.push(h)}}return this.c=a.join("&")};f.$=function(a){U(this);this.a.forEach(function(b,c){0<=La(a,c)||Bc(this,c)},this);return this};function rc(a){var b=new sc;b.c=a.c;a.a&&(b.a=new hc(a.a),b.b=a.b);return b}
function V(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b}function yc(a,b){b&&!a.f&&(U(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Bc(this,d),Ac(this,e,c))},a));a.f=b}f.ma=function(a){for(var b=0;b<arguments.length;b++)lc(arguments[b],function(c,d){this.add(d,c)},this)};var Ec={};function Fc(a,b){var c=Ec[a];if(void 0!==c&&(!c.H||Date.now()<=c.H+3E5))return c.p;c=new Promise(function(e,g){b.onload=function(){return e(b)};b.onerror=function(h){b.parentNode&&b.parentNode.removeChild(b);g(h)};document.head.appendChild(b)});var d={H:0,p:c};c.catch(function(){return d.H=+new Date});Ec[a]=d;return c}
function Gc(a){var b=void 0===b?null:b;a=a instanceof R?new R(a):new R(a,void 0);var c=document.createElement("script");c.src=a.toString();b&&(c.type=b);return Fc(a.toString(),c)};var Hc=!t||9<=Number(mb),Ic=!t||9<=Number(mb),Jc;
if(Jc=t){var Kc;if(Object.prototype.hasOwnProperty.call(jb,"9"))Kc=jb["9"];else{for(var Lc=0,Mc=Ua(String(ib)).split("."),Nc=Ua("9").split("."),Oc=Math.max(Mc.length,Nc.length),Pc=0;0==Lc&&Pc<Oc;Pc++){var Qc=Mc[Pc]||"",Rc=Nc[Pc]||"";do{var W=/(\d*)(\D*)(.*)/.exec(Qc)||["","","",""],X=/(\d*)(\D*)(.*)/.exec(Rc)||["","","",""];if(0==W[0].length&&0==X[0].length)break;Lc=Va(0==W[1].length?0:parseInt(W[1],10),0==X[1].length?0:parseInt(X[1],10))||Va(0==W[2].length,0==X[2].length)||Va(W[2],X[2]);Qc=W[3];
Rc=X[3]}while(0==Lc)}Kc=jb["9"]=0<=Lc}Jc=!Kc}var Sc=Jc,Tc=function(){if(!n.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{n.addEventListener("test",Aa,b),n.removeEventListener("test",Aa,b)}catch(c){}return a}();function Uc(){this.s=this.s;this.b=this.b}f=Uc.prototype;f.s=!1;f.N=function(){return this.s};f.ca=Uc.prototype.N;f.C=function(){this.s||(this.s=!0,this.D())};f.Xa=function(a){a=Ea(Vc,a);this.s?a():(this.b||(this.b=[]),this.b.push(a))};f.D=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function Vc(a){a&&"function"==typeof a.C&&a.C()};function Wc(a,b){this.type=a;this.b=this.target=b;this.G=this.f=!1}Wc.prototype.g=function(){this.f=!0};Wc.prototype.c=function(){this.G=!0};function Y(a,b){Wc.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.o=this.j=0;this.key="";this.h=this.i=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.F=null;this.I=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(ab){a:{try{Ya(b.nodeName);
var e=!0;break a}catch(g){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.j=bb||void 0!==a.offsetX?a.offsetX:a.layerX,this.o=bb||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.i=a.keyCode||0;this.key=a.key||"";this.h=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.I=cb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Xc[a.pointerType]||"";this.F=a.state;this.a=a;a.defaultPrevented&&this.c()}}Ha(Y,Wc);var Yc=[1,4,2],Xc={2:"touch",3:"pen",4:"mouse"};
Y.prototype.pb=function(){return(Hc?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Yc[0]))&&!(bb&&cb&&this.ctrlKey)};Y.prototype.g=function(){Y.J.g.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};Y.prototype.c=function(){Y.J.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Sc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Zc="closure_listenable_"+(1E6*Math.random()|0),$c=0;function ad(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++$c;this.v=this.B=!1}function bd(a){a.v=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function cd(a){this.src=a;this.a={};this.b=0}f=cd.prototype;f.ta=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};f.add=function(a,b,c,d,e){var g=a.toString();a=this.a[g];a||(a=this.a[g]=[],this.b++);var h=dd(a,b,d,e);-1<h?(b=a[h],c||(b.B=!1)):(b=new ad(b,this.src,g,!!d,e),b.B=c,a.push(b));return b};
f.va=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=dd(e,b,c,d);return-1<b?(bd(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};f.wa=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,bd(d[e]);delete this.a[c];this.b--}return b};f.ea=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
f.ua=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Ta(this.a,function(g){for(var h=0;h<g.length;++h)if(!(c&&g[h].type!=d||e&&g[h].capture!=b))return!0;return!1})};function dd(a,b,c,d){for(var e=0;e<a.length;++e){var g=a[e];if(!g.v&&g.listener==b&&g.capture==!!c&&g.b==d)return e}return-1};var ed="closure_lm_"+(1E6*Math.random()|0),fd={},gd=0;function hd(a,b,c,d,e){if(d&&d.once)return id(a,b,c,d,e);if(Array.isArray(b)){for(var g=0;g<b.length;g++)hd(a,b[g],c,d,e);return null}c=jd(c);return a&&a[Zc]?kd(a,b,c,Da(d)?!!d.capture:!!d,e):ld(a,b,c,!1,d,e)}
function ld(a,b,c,d,e,g){if(!b)throw Error("Invalid event type");var h=Da(e)?!!e.capture:!!e,k=md(a);k||(a[ed]=k=new cd(a));c=k.add(b,c,d,h,g);if(c.a)return c;d=nd();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Tc||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(od(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");gd++;return c}
function nd(){var a=pd,b=Ic?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function id(a,b,c,d,e){if(Array.isArray(b)){for(var g=0;g<b.length;g++)id(a,b[g],c,d,e);return null}c=jd(c);return a&&a[Zc]?a.c(b,c,Da(d)?!!d.capture:!!d,e):ld(a,b,c,!0,d,e)}
function qd(a){if("number"!==typeof a&&a&&!a.v){var b=a.src;if(b&&b[Zc])b.f(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(od(c),d):b.addListener&&b.removeListener&&b.removeListener(d);gd--;if(c=md(b)){d=a.type;if(d in c.a){var e=c.a[d],g=La(e,a),h;(h=0<=g)&&Array.prototype.splice.call(e,g,1);h&&(bd(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[ed]=null)}else bd(a)}}}
function od(a){return a in fd?fd[a]:fd[a]="on"+a}function rd(a,b,c,d){var e=!0;if(a=md(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.v&&(g=sd(g,d),e=e&&!1!==g)}return e}function sd(a,b){var c=a.listener,d=a.b||a.src;a.B&&qd(a);return c.call(d,b)}
function pd(a,b){if(a.v)return!0;if(!Ic){var c=b||za("window.event");b=new Y(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.b;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.f&&0<=e;e--){b.b=c[e];var g=rd(c[e],a,!0,b);d=d&&g}for(e=0;!b.f&&e<c.length;e++)b.b=c[e],g=rd(c[e],a,!1,b),d=d&&g}return d}return sd(a,new Y(b,this))}
function md(a){a=a[ed];return a instanceof cd?a:null}var td="__closure_events_fn_"+(1E9*Math.random()>>>0);function jd(a){if("function"==Ba(a))return a;a[td]||(a[td]=function(b){return a.handleEvent(b)});return a[td]};function ud(a){Uc.call(this);this.c=a;this.a={}}Ha(ud,Uc);var vd=[];f=ud.prototype;f.Qa=function(a,b,c,d,e){return kd(this,a,b,c,d,e)};function kd(a,b,c,d,e,g){Array.isArray(c)||(c&&(vd[0]=c.toString()),c=vd);for(var h=0;h<c.length;h++){var k=hd(b,c[h],d||a.handleEvent,e||!1,g||a.c||a);if(!k)break;a.a[k.key]=k}return a}function wd(a,b){xd(Z.b,a,"devsite-content-updated",b,void 0)}f.Pa=function(a,b,c,d,e){return xd(this,a,b,c,d,e)};
function xd(a,b,c,d,e,g){if(Array.isArray(c))for(var h=0;h<c.length;h++)xd(a,b,c[h],d,e,g);else{b=id(b,c,d||a.handleEvent,e,g||a.c||a);if(!b)return a;a.a[b.key]=b}return a}f.Ra=function(a,b,c,d){kd(b,a,c,d,this.c||this);return this};f.Sa=function(a,b,c,d,e){kd(b,a,c,d,e||this.c||this);return this};f.sa=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function yd(a,b,c,d,e,g){if(Array.isArray(c))for(var h=0;h<c.length;h++)yd(a,b,c[h],d,e,g);else d=d||a.handleEvent,e=Da(e)?!!e.capture:!!e,g=g||a.c||a,d=jd(d),e=!!e,b&&b[Zc]?c=b.a(c,d,e,g):b?(b=md(b))?(c=b.a[c.toString()],b=-1,c&&(b=dd(c,d,e,g)),c=-1<b?c[b]:null):c=null:c=null,c&&(qd(c),delete a.a[c.key])}f.qb=function(a,b,c,d,e){yd(b,a,c,d,e||this.c||this,this);return this};function zd(a){Sa(a.a,function(b,c){this.a.hasOwnProperty(c)&&qd(b)},a);a.a={}}f.D=function(){ud.J.D.call(this);zd(this)};
f.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Ad(){var a=this;if(za("__globalAppLoader"))return za("__globalAppLoader");this.c=null;this.h=!1;this.b=new ud;this.f=[];this.g=function(b){a.f.push(b)};try{this.a=ec()}catch(b){Bd("GoogleDevelopersObject missing or invalid")}GoogleDevelopersObject=null;Ga("__globalAppLoader",this)}Ad.prototype.C=function(){zd(this.b)};
function Cd(a){var b=[];b.push(Gc(K(a.a,5,"")+"/js/webcomponents-lite.js"));"fetch"in window&&"URL"in window||b.push(Gc(K(a.a,5,"")+"/js/polyfills.js"));return Promise.all(b)}
function Dd(){var a=Ed,b,c,d,e,g;return ya(new xa(new ta(function(h){switch(h.a){case 1:return t&&document.body.setAttribute("ie-"+parseInt(ib,10),""),h.c=2,pa(h,Cd(a),4);case 4:qa(h,3);break;case 2:b=ra(h),Bd("Failed to load Devsite App dependencies: "+b.message);case 3:return c=new Promise(function(k){Ga("__devsiteAppReadyResolver",k)}),Ga("__devsiteAppReadyPromise",c),Ga("DevsiteApp.whenReady",function(){return c}),h.c=5,pa(h,Gc(K(a.a,6,"")+(a.a.getLocale()&&"en"!=a.a.getLocale()?K(a.a,4,"").replace(/\.js$/,
"__"+a.a.getLocale().toLowerCase().replace("-","_")+".js"):K(a.a,4,""))),7);case 7:qa(h,6);break;case 5:d=ra(h);if("en"===a.a.getLocale()){Bd("Failed to load Devsite App binary: "+d.message);h.u(6);break}M(a.a,2,"en","");h.c=9;return pa(h,Gc(K(a.a,6,"")+K(a.a,4,"")),11);case 11:qa(h,6);break;case 9:e=ra(h),Bd("Failed to load Devsite App binary: "+e.message);case 6:if(g=document,"complete"===g.readyState)h.u(0);else return pa(h,new Promise(function(k){g.addEventListener("readystatechange",function(){"complete"===
g.readyState&&k()})}),0)}})))}function Bd(a){throw new function(b){this.message=b;this.name="DevsiteAppLoaderException"}(void 0===a?"Devsite has failed to load.":a);};var Z=new Ad;(function(){var a=document.querySelector("devsite-content");a&&(kd(Z.b,window,"message",Z.g,void 0),wd(a,function(){yd(Z.b,window,"message",Z.g);for(var b=ba(Z.f),c=b.next();!c.done;c=b.next())window.dispatchEvent(c.value.a);Z.f=[]}))})();var Fd;var Ed=Z;"WeakMap"in window&&"performance"in window&&"now"in window.performance?(Ed.c||(Ed.c=Dd()),Fd=Ed.c):Fd=Promise.resolve();
Fd.then(function(){za("DevsiteAppInit")||Bd("Failed to load Devsite App binary");L(Z.a,9)?DevsiteAppFrameboxInit(Z.a.M(),DevsiteAppAuthorizedElements):DevsiteAppInit(Z.a.M(),DevsiteAppAuthorizedElements,DevsiteAppCoreElements)});}).call(this);
